import * as URL from './url'

export { URL }

export const MENUS = [{
  icon: 'msg',
  path: '/msg',
  key: 'msg'
}, {
  icon: 'contacts',
  path: '/contacts',
  key: 'contacts'
}, {
  icon: 'cloud',
  path: '/cloud',
  key: 'cloud'
}, {
  icon: 'app',
  path: '/apps', // 与js/app目录区别开
  key: 'app'
}]

export const SETTINGKEY = 'SETTING'

export const HYDRATE_STATE = 'HYDRATE_STATE'

// im token失效code
export const INVALID_TOKEN = 'IMCORE/WEBIM_INVALID_TOKEN'

// im服务端错误，token刷新次数
export const IM_TOKEN_REFRESH_TIMES = 5

export const NETWORK_ERROR = 'Network Error'

export const MSG_TYPE = {
  ARTICLE: 'article',
  AUDIO: 'audio',
  BOX: 'box',
  CTL: 'ctl',
  DOCSYNC: 'docsync',
  EVENT: 'event',
  FILE: 'file',
  FOLDER: 'folder',
  IMG: 'img',
  LINK: 'link',
  NTF: 'ntf',
  RICH: 'rich',
  STREAM: 'stream',
  SYS: 'sys',
  TEL: 'tel',
  TEXT: 'text',
  TIP: 'tip',
  VIDEO: 'video',
  UNSUPPORTED: 'unsupported',
  LOCAL_NOTICE: 'local_notice' // 本地通知，如@提醒
}

// 控制消息 ctl/json <不需要记录消息，只作在线转发>
export const CTL_MSG_TYPE = {
  TYPEING: 'TYPING',
  SHAKE_WINDOW: 'SHAKE_WINDOW',
  RECALL_MESSAGE: 'RECALL_MESSAGE'
}

/**
 * 会话邀请消息
 * @see http://wiki.sdp.nd/index.php?title=%E4%BC%9A%E8%AE%AE%E9%82%80%E8%AF%B7
 */
export const TEL_MSG_TYPE = {
  TELE_P2P_CALL_REQ: 'TELE_P2P_CALL_REQ',
  TELE_P2P_CALL_RSP: 'TELE_P2P_CALL_RSP',
  TELE_P2P_CALL_ACCEPT_NTF: 'TELE_P2P_CALL_ACCEPT_NTF',
  TELE_P2P_CALL_SUCCESS_NTF: 'TELE_P2P_CALL_SUCCESS_NTF',
  TELE_P2P_CALL_DISC_NTF: 'TELE_P2P_CALL_DISC_NTF'
}

/**
 * 业务通知消息
 * see http://wiki.sdp.nd/index.php?title=IM_%E6%B6%88%E6%81%AF%E6%A0%BC%E5%BC%8F%E5%8D%8F%E8%AE%AE_SDP2.0#.E4.B8.9A.E5.8A.A1.E9.80.9A.E7.9F.A5.E6.B6.88.E6.81.AF
 */
export const NTF_MSG_TYPE = {
  GRP_CREATED: 'GRP_CREATED',
  GRP_INFO_CHANGED: 'GRP_INFO_CHANGED',
  GRP_MB_ADDED: 'GRP_MB_ADDED',
  GRP_MB_GRD_CHANGED: 'GRP_MB_GRD_CHANGED',
  GRP_MB_CHANGED: 'GRP_MB_CHANGED',
  GRP_MB_DELETED: 'GRP_MB_DELETED',
  GRP_MB_EXIT: 'GRP_MB_EXIT',
  GRP_ICON_CHANGED: 'GRP_ICON_CHANGED',
  NTF_GRP_DISMISSED: 'NTF_GRP_DISMISSED',
  NTF_GRP_MB_DELETED: 'NTF_GRP_MB_DELETED',
  NTF_GRP_MB_EXIT: 'NTF_GRP_MB_EXIT',
  NTF_GRP_INVITE: 'NTF_GRP_INVITE',
  NTF_GRP_INVITE_ACCEPTED: 'NTF_GRP_INVITE_ACCEPTED',
  NTF_GRP_INVITE_REFUSED: 'NTF_GRP_INVITE_REFUSED',
  NTF_GRP_REQUEST: 'NTF_GRP_REQUEST',
  NTF_GRP_REQUEST_ACCEPTED: 'NTF_GRP_REQUEST_ACCEPTED',
  NTF_GRP_REQUEST_REFUSED: 'NTF_GRP_REQUEST_REFUSED',
  NTF_RELATED_GRP_DEL: 'NTF_RELATED_GRP_DEL',
  NTF_GRP_ORGNODE_INACTIVE: 'NTF_GRP_ORGNODE_INACTIVE',
  NTF_FRD_REQUEST: 'NTF_FRD_REQUEST',
  NTF_FRD_WITHOUT_APPROVAL: 'NTF_FRD_WITHOUT_APPROVAL',
  NTF_FRD_DECLINE: 'NTF_FRD_DECLINE',
  NTF_REQ_DELETE: 'NTF_REQ_DELETE',
  NTF_FRD_EDIT: 'NTF_FRD_EDIT',
  NTF_FRD_DELETE: 'NTF_FRD_DELETE',
  NTF_TAG_ADD: 'NTF_TAG_ADD',
  NTF_TAG_EDIT: 'NTF_TAG_EDIT',
  NTF_TAG_DELETE: 'NTF_TAG_DELETE',
  NTF_BLK_ADD: 'NTF_BLK_ADD',
  NTF_BLK_DELETE: 'NTF_BLK_DELETE',
  NTF_CONCERN_ADD: 'NTF_CONCERN_ADD',
  NTF_CONCERN_DELETE: 'NTF_CONCERN_DELETE',
  FRD_APPROVAL: 'FRD_APPROVAL',
  OA_SUBSCRIBE: 'OA_SUBSCRIBE',
  OA_UNSUBSCRIBE: 'OA_UNSUBSCRIBE',
  OA_COLLECT: 'OA_COLLECT',
  OA_UNCOLLECT: 'OA_UNCOLLECT',
  OA_CHANGE_INFO: 'OA_CHANGE_INFO',
  OA_CHANGE_MENU: 'OA_CHANGE_MENU',
  OA_CANCEL: 'OA_CANCEL',
  POL_ND_CHANGE: 'POL_ND_CHANGE'
}

/**
 * p2p流消息
 * see http://wiki.sdp.nd/index.php?title=%E6%96%B0IM%E6%B6%88%E6%81%AF%E8%A7%84%E8%8C%83#stream.2Fxml_P2P.E6.B5.81
 */
export const STREAM_MSG_TYPE = {
  ACTION: {
    OFFER_REQUEST: 'offer_request',
    SENDER_CLOSE: 'sender_close',
    RECVER_CLOSE: 'recver_close'
  },
  CLOSE_REASON: {
    CLOSE_OF_CANCEL: 0,
    CLOSE_OF_FINISH: 1,
    CLOSE_OF_NETWORK_ERROR: 2,
    CLOSE_OF_FILE_IO_ERROR: 3,
    CLOSE_OF_REFUSED: 4,
    CLOSE_OF_USE_OFFLINE_INSTEAD: 5
  }
}

// 忽略的消息类型
export const IGNORE_MSG_TYPE = [
  CTL_MSG_TYPE.TYPEING,
  NTF_MSG_TYPE.GRP_CREATED,
  NTF_MSG_TYPE.GRP_MB_ADDED,
  NTF_MSG_TYPE.GRP_MB_GRD_CHANGED,
  NTF_MSG_TYPE.GRP_MB_CHANGED,
  NTF_MSG_TYPE.GRP_MB_DELETED,
  NTF_MSG_TYPE.GRP_MB_EXIT,
  NTF_MSG_TYPE.GRP_ICON_CHANGED,
  NTF_MSG_TYPE.NTF_GRP_MB_DELETED,
  NTF_MSG_TYPE.NTF_GRP_MB_EXIT,
  NTF_MSG_TYPE.NTF_RELATED_GRP_DEL,
  NTF_MSG_TYPE.NTF_FRD_WITHOUT_APPROVAL,
  NTF_MSG_TYPE.NTF_TAG_ADD,
  NTF_MSG_TYPE.NTF_TAG_EDIT,
  NTF_MSG_TYPE.NTF_TAG_DELETE,
  NTF_MSG_TYPE.NTF_BLK_ADD,
  NTF_MSG_TYPE.NTF_BLK_DELETE,
  NTF_MSG_TYPE.NTF_CONCERN_ADD,
  NTF_MSG_TYPE.NTF_CONCERN_DELETE,
  NTF_MSG_TYPE.OA_SUBSCRIBE,
  NTF_MSG_TYPE.OA_UNSUBSCRIBE,
  NTF_MSG_TYPE.OA_COLLECT,
  NTF_MSG_TYPE.OA_UNCOLLECT,
  NTF_MSG_TYPE.POL_ND_CHANGE // todo 暂时忽略免打扰策略变化消息
]

export const LANGUAGES = ['zh-CN', 'en-US']
