export const PULL = 'MSG/PULL'
export const CANCEL_POLLING = 'MSG/CANCEL_POLLING'

export const RECEIVE_MESSAGES = 'MSG/RECEIVE_MESSAGES'
export const RECEIVE_READ_NOTICES = 'MSG/RECEIVE_READ_NOTICES'
export const SEND_MESSAGE = 'MSG/SEND_MESSAGE'
export const ACK_INBOX_MSG = 'MSG/ACK_INBOX_MSG'
export const MARK_CONV_MSG_READ = 'MSG/MARK_CONV_MSG_READ'
export const GET_CONV_MSG = 'MSG/GET_CONV_MSG'

export const INIT_CONVERSATIONS = 'MSG/INIT_CONVERSATIONS'
export const INIT_MESSAGES = 'MSG/INIT_MESSAGES'
export const REMOVE_MESSAGE = 'MSG/REMOVE_MESSAGE'
export const UPDATE_MESSAGE = 'MSG/UPDATE_MESSAGE'

export const GET_CONVERSATIONS = 'MSG/GET_CONVERSATIONS'
export const SET_TYPING_P2P_CONVERSATIONS = 'MSG/SET_TYPING_P2P_CONVERSATIONS'
export const ADD_P2P_CONVERSATION = 'MSG/ADD_P2P_CONVERSATION'
export const ADD_OR_UPDATE_GROUP_CONVERSATION = 'MSG/ADD_OR_UPDATE_GROUP_CONVERSATION'
export const REMOVE_CONVERSATIONS = 'MSG/REMOVE_CONVERSATIONS'

export const SET_CURRENT_CONVID = 'MSG/SET_CURRENT_CONVID'
export const GET_EMOTION_PACKAGES = 'MSG/GET_EMOTION_PACKAGES'
export const OFFLINE = 'MSG/OFFLINE'

export const PLAY_AUDIO = 'MSG/PLAY_AUDIO'
export const UPDATE_LOCAL_MESSAGE = 'MSG/UPDATE_LOCAL_MESSAGE'

export const CLEAR_CONVERSATION_MSGS = 'MSG/CLEAR_CONVERSATION_MSGS'
export const UPDATE_CONVERSATION = 'MSG/UPDATE_CONVERSATION'
export const SEND_TYPING_MESSAGE = 'MSG/SEND_TYPING_MESSAGE'
export const SLICE_CONV_MSGS = 'MSG/SLICE_CONV_MSGS'

export const TRANSLATE_CONV_MSGS = 'MSG/TRANSLATE_CONV_MSGS'
export const TRANSLATE_CONVERSATIONS = 'MSG/TRANSLATE_CONVERSATIONS'
